"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['YandexMusicApp.py']
DATA_FILES = []
OPTIONS = {
    'plist': {
        'CFBundleGetInfoString': 'Веб версия Яндекс Музыки',
        'CFBundleVersion': '0.1.0',
        'CFBundleShortVersionString': '0.1.0',
    },

    'iconfile': 'logo.png',
    # 'packages': ['PyQt5', 'PyQt5.QtWebEngine', 'PyQt5.QtWebEngineWidgets'],
    # 'includes': ['sip'],
    # 'excludes': ['PyQt5.QtDesigner'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
